### PR TITLE
 Add until option

### PR DESCRIPTION
**Pull request by braffes**
Add until option to permit to set the `endtime` arg of sacct.

### CODE REVIEW

**Comment by troycomi** [comment]
Nice feature and even better refactoring!  Thanks for the contribution.

GHA is failing because of dependencies.  If you can fix those I'll merge otherwise this will have to wait until after the new year when I have a little more time to work on this.

**Comment by braffes** [comment]
To fix the dependencies issue, we have 2 choices.
- Upgrade pytest package to the version 7.2.0 where there is no more usage of the library "py" which is vulnerable. But it implies to remove the support of python 3.6 (cf: https://docs.pytest.org/en/7.2.x/changelog.html#pytest-7-2-0-2022-10-23)
- Add the argument "--ignore 51457" in the noxfile.py. 

I don't know what is your opinion about that, tell me, And I can do the changes.

**Comment by troycomi** [comment]
Let's go ahead and drop 3.6.

**Comment by troycomi** [comment]
Let me have a crack at getting the tests to pass tomorrow, will be faster than this push/run cycle.

Thanks again for the effort!

**Comment by troycomi** [comment]
Can you allow edits by maintainers?  Otherwise, I think I have it passes with:
- add `ANN401` to `.flake8` ignore
- bump setup-python in all GHA workflows to `@v2`, `poetry==1.3.1`, and `nox==22.11.21`
That's working well enough with act to try the workflow again.

**Comment by braffes** [comment]
It's already checked, no?

I broke my environment yesterday, that's why there is some weird thing with the poetry file I think.

If it doesn't work, I will retry today later a new commit with your recommendation.

**Comment by troycomi** [comment]
Phew, that was a lot of version bumping.  Thank you for your patience in all this!  Will release a minor version change with this feature shortly.

**Pull request merged**
